### ISSUE TITLE
Add a calendar view, click to jump to the corresponding heading

### ISSUE THREAD

**Issue by calmwaves111** [pranavmangal/obsidian-single-file-daily-notes#2]
Thank you very much for this plugin. I have the same problem as you, and I don't want to have hundreds or thousands of daily notes, especially when they were quite small individually
But using the built-in outline view is too long, I think the calendar view is more intuitive
Obsedian has many calendar plugins, but they are all based on files.
It would be great if this plugin could create a calendar view and navigate to the corresponding heading by clicking on it

**Comment by pranavmangal** [comment]
Glad that this could be of some use to you and thanks for the feature request.

Personally, I just use `Cmd + F` for finding a particular date, but I can see that having a calendar view could be useful for others (and perhaps for more features down the road).

I will try implementing some basic calendar functionality and will update here once that's done.

**Comment by pranavmangal** [comment]
@calmwaves111 Sorry for the delay, I kind of forgot about this plugin. 
This has now been implemented, so I am closing this issue.

Feel free to open it again in case you face any problems.

**Comment by calmwaves111** [comment]
Thank you for your hard work. It's really amazing
I think it's more intuitive to put a dot under the date with the diary in the calendar view
