### ISSUE TITLE
Not understand how it work

### ISSUE THREAD

**Issue by dxcore35** [pranavmangal/obsidian-single-file-daily-notes#4]
- is this file update everytime I create daily note manualy?
- I have 50 daily notes all is set but this single note is empty
- do I have to trigger the create daily note? or I just need to open it?
- is the text rof all notes really in that file?

Many questions how this plugin actually work

**Comment by pranavmangal** [comment]
Hey @dxcore35, to answer your questions:

1. The daily notes created with the in-built plugin are not in anyway connected with this plugin. So creating daily notes through that will not affect the single daily notes file. This plugin is intended to be a replacement for Obsidian's built-in functionality.
2. There is currently no import functionality built into the plugin, so your existing daily notes won't show up in the single file. This is something I can try to add, it could be useful for people already having large collections of notes.
3. Just opening the file should create a blank note for the day.
4. Yes, that file is intended to be the source of truth and all the data for the notes is contained in it. It is not special in any way, it is a standard markdown file.
