### ISSUE TITLE
Incompatible with obsidian properties

### ISSUE THREAD

**Issue by calmwaves111** [pranavmangal/obsidian-single-file-daily-notes#5]
If the md file where the diary is stored has properties in its header, the contents of the new diary will still appear above it

**Comment by jcesguerram** [comment]
> If the md file where the diary is stored has properties in its header, the contents of the new diary will still appear above it

+1. this is important. i tried to add a banner to the note, but it is messed up each time the note is opened

**Comment by pranavmangal** [comment]
I have pushed an update that should now make this plugin compatible with Obsidian properties.
