### ISSUE TITLE
Automatic Sorting of Notes by Date

### ISSUE THREAD

**Issue by alitekdemir** [pranavmangal/obsidian-single-file-daily-notes#6]
Hi,

I am using the Single File Daily Notes plugin and I am experiencing an issue with the sorting of notes by date. When notes are added out of chronological order, the plugin does not automatically sort them. This results in a disorganized list of notes, as shown in the attached screenshot.

Feature Request:
Implement a feature that ensures notes are automatically sorted by date whenever a new note is added or an existing note is modified.

<img src="https://github.com/pranavmangal/obsidian-single-file-daily-notes/assets/1507344/9c963ec3-e15c-49a2-b15f-12cc5326ede8" width="200">

**Comment by jcesguerram** [comment]
how do you get the name of the day in your language?

**Comment by alitekdemir** [comment]
> how do you get the name of the day in your language?

The names of the days are below.

| English   | Turkish   |
| --------- | --------- |
| Monday    | Pazartesi |
| Tuesday   | Salı      |
| Wednesday | Çarşamba  |
| Thursday  | Perşembe  |
| Friday    | Cuma      |
| Saturday  | Cumartesi |

**Comment by jcesguerram** [comment]
yeah but how do you get it to show in that language and not english?

**Comment by alitekdemir** [comment]
> yeah but how do you get it to show in that language and not english?

I understand now. The screenshot I shared is not suitable for sorting by name. DD-MM-YYYY would not be suitable. Actually the name is not important, if possible the file name or alternatively an extra date yaml value can be used to sort.

**Comment by pranavmangal** [comment]
@alitekdemir I would recommend using the built-in calendar view to insert new notes out of order. It should automatically parse your file and insert the note in the right place for any date (past or future). Using this method, you should never have any out-of-order dates.

It would be quite expensive to check the entire file for out-of-order dates on every edit, as doing this would require parsing and (potentially) rewriting the entire file everytime.

**Comment by pranavmangal** [comment]
@jcesguerram this plugin uses Obsidian's built-in [moment.js](https://momentjs.com/) library. It will determine the display language used in Obsidian and display the dates in that language. Here `alitekdemir` must have set his language to Turkish, which is why they see the day names in Turkish. 

You can change it for your vault by changing the language by going to `Settings` -> `General` -> `Language`.
