### ISSUE TITLE
Do Calendar and Periodic Notes plugins need to be disabled?

### ISSUE THREAD

**Issue by jcesguerram** [pranavmangal/obsidian-single-file-daily-notes#8]
Do the Calendar and Periodic Notes plugins need to be disabled for this plugin to work?
Or can they coexist?

**Comment by pranavmangal** [comment]
This plugin is a completely separate entity from the built-in daily notes plugin, on top of which I believe the Calendar and Periodic Notes plugins operate. They don't need to be disabled per se, but they will only operate on the core plugin and not this plugin, so they won't be of any use. I have updated the Readme to better reflect that.

Co-existing with the core plugin will require perpetual synchronisation between it's files and the single file provided by this plugin, which I don't think would be ideal. Instead, I might look into implementing some kind of one time import/export to switch between the two systems.
